name: causal
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - matplotlib
  - statsmodels
  - seaborn
  # - flaml[ray]
  # - plotly
  - pip
  - pip:
    - toml
    - fastparquet
    - graphviz
# statsmodels
# seaborn
# pycaret
# toml
# fastparquet